### ISSUE TITLE
Proposal: Style PDF bookmarks to chapters in bold

### ISSUE THREAD

**Issue by LinqLover** [krono/swathesis#62]
![image](https://github.com/krono/swathesis/assets/38782922/c853c4a6-2361-4743-90d5-0a959df3cb63)

```tex
\usepackage{bookmark}
\makeatletter
\bookmarksetup{
	open,
	addtohook={%
		\ifnum\bookmarkget{level}=0 %
			\if@mainmatter
				\bookmarksetup{bold}%
			\fi
		\fi
	},
}
\makeatother
```

If this is relevant, I can send a patch. Otherwise, sorry for the noise. :)

**Comment by krono** [comment]
No need to be sorry.
I think this is somewhat nice, but a tad too specific for my taste.
`bookmark` is loaded at the right place in `swa-document` already , so probably a prper `\AfterPackage` or `\BeforeBeginEnvrionemnt{document}` is in order to not disturb hyperref and friends.

Maybe i should add something to customize swathesis properli (viz `lstlang0.sty` of listings…)

**Comment by LinqLover** [comment]
I'm not sure whether this was advice on how to refactor my personal solution or a request for creating a pull request :sweat_smile:

**Comment by krono** [comment]
na just rambling
